CREATE TABLE activities (
    id CHAR(36) PRIMARY KEY, 
    user_id CHAR(36) NOT NULL, 
    activity_type VARCHAR(255) NOT NULL,
    done_at TIMESTAMP(3) NOT NULL,
    duration_in_minutes INT NOT NULL,
    calories_burned INT NOT NULL,
    created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    CONSTRAINT fk_user_id FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
